"""alters auditions column names

Revision ID: 719a36b52e67
Revises: fe0b50af308f
Create Date: 2023-07-18 13:05:42.444096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719a36b52e67'
down_revision = 'fe0b50af308f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_accepted', sa.Boolean(), nullable=True))
        batch_op.drop_column('band_accepts')
        batch_op.drop_column('musician_accepts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('musician_accepts', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('band_accepts', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_accepted')
        batch_op.drop_column('requested_by')

    # ### end Alembic commands ###
